/**
 * Mock Groups Data
 */
import type { Group } from '@/shared/types';

export const mockGroups: Group[] = [
    // ABC Company Groups
    {
        id: 'group-001',
        orgId: 'org-001',
        name: 'Phòng Kinh Doanh',
        description: 'Business strategy and development team',
        privacyLevel: 'internal',
        createdAt: new Date('2025-01-05'),
        updatedAt: new Date('2025-01-18'),
        createdBy: 'user-001',
        memberCount: 5,
        meetingCount: 24,
        totalHours: 68,
    },

    {
        id: 'group-002',
        orgId: 'org-001',
        name: 'Phòng Kỹ Thuật',
        description: 'Engineering and development team',
        privacyLevel: 'internal',
        createdAt: new Date('2025-01-08'),
        updatedAt: new Date('2025-01-19'),
        createdBy: 'user-004',
        memberCount: 8,
        meetingCount: 45,
        totalHours: 125,
    },

    {
        id: 'group-003',
        orgId: 'org-001',
        name: 'Ban Giám Đốc',
        description: 'Executive management team',
        privacyLevel: 'private',
        createdAt: new Date('2025-01-12'),
        updatedAt: new Date('2025-01-17'),
        createdBy: 'user-001',
        memberCount: 5,
        meetingCount: 22,
        totalHours: 55,
    },

    // Global Corp Groups (org-002)
    {
        id: 'group-004',
        orgId: 'org-002',
        name: 'Phát triển AI',
        description: 'Đội ngũ kỹ thuật nòng cốt phát triển trí tuệ nhân tạo',
        privacyLevel: 'internal',
        createdAt: new Date('2025-02-03'),
        updatedAt: new Date('2025-02-09'),
        createdBy: 'user-007',
        memberCount: 8,
        meetingCount: 34,
        totalHours: 92,
    },

    {
        id: 'group-005',
        orgId: 'org-002',
        name: 'Sales Team',
        description: 'Sales and business development',
        privacyLevel: 'internal',
        createdAt: new Date('2025-02-04'),
        updatedAt: new Date('2025-02-08'),
        createdBy: 'user-007',
        memberCount: 7,
        meetingCount: 33,
        totalHours: 50,
    },

    // Tech Startup groups (org-003)
    {
        id: 'group-006',
        orgId: 'org-003',
        name: 'Product Team',
        description: 'Product management and strategy',
        privacyLevel: 'internal',
        createdAt: new Date('2025-03-05'),
        updatedAt: new Date(),
        createdBy: 'user-011',
        memberCount: 5,
        meetingCount: 18,
        totalHours: 36,
    },
    {
        id: 'group-007',
        orgId: 'org-003',
        name: 'Engineering',
        description: 'Core engineering and development',
        privacyLevel: 'internal',
        createdAt: new Date('2025-03-08'),
        updatedAt: new Date(),
        createdBy: 'user-011',
        memberCount: 7,
        meetingCount: 25,
        totalHours: 58,
    },
    {
        id: 'group-008',
        orgId: 'org-003',
        name: 'Marketing',
        description: 'Marketing and growth team',
        privacyLevel: 'public',
        createdAt: new Date('2025-03-10'),
        updatedAt: new Date(),
        createdBy: 'user-011',
        memberCount: 3,
        meetingCount: 12,
        totalHours: 24,
    },

    // Global Education groups (org-004)
    {
        id: 'group-009',
        orgId: 'org-004',
        name: 'Phòng Đào Tạo',
        description: 'Quản lý đào tạo và chương trình học',
        privacyLevel: 'internal',
        createdAt: new Date('2025-01-20'),
        updatedAt: new Date(),
        createdBy: 'user-011',
        memberCount: 8,
        meetingCount: 32,
        totalHours: 78,
    },
    {
        id: 'group-010',
        orgId: 'org-004',
        name: 'Phòng Tuyển Sinh',
        description: 'Tuyển sinh và tư vấn học viên',
        privacyLevel: 'internal',
        createdAt: new Date('2025-01-22'),
        updatedAt: new Date(),
        createdBy: 'user-011',
        memberCount: 6,
        meetingCount: 24,
        totalHours: 52,
    },
    {
        id: 'group-011',
        orgId: 'org-004',
        name: 'Ban Giám Hiệu',
        description: 'Ban lãnh đạo tập đoàn',
        privacyLevel: 'private',
        createdAt: new Date('2025-01-18'),
        updatedAt: new Date(),
        createdBy: 'user-011',
        memberCount: 4,
        meetingCount: 15,
        totalHours: 38,
    },
    {
        id: 'group-012',
        orgId: 'org-004',
        name: 'Phòng Tài Chính',
        description: 'Quản lý tài chính và kế toán',
        privacyLevel: 'internal',
        createdAt: new Date('2025-01-25'),
        updatedAt: new Date(),
        createdBy: 'user-011',
        memberCount: 5,
        meetingCount: 18,
        totalHours: 42,
    },
    {
        id: 'group-013',
        orgId: 'org-004',
        name: 'Phòng CNTT',
        description: 'Hạ tầng và công nghệ thông tin',
        privacyLevel: 'internal',
        createdAt: new Date('2025-02-01'),
        updatedAt: new Date(),
        createdBy: 'user-011',
        memberCount: 4,
        meetingCount: 14,
        totalHours: 32,
    },
];

export const groupMap = new Map(mockGroups.map(g => [g.id, g]));
export const getGroupById = (id: string): Group | undefined => groupMap.get(id);
export const getGroupsByIds = (ids: string[]): Group[] =>
    ids.map(id => groupMap.get(id)).filter(Boolean) as Group[];
export const getGroupsByOrgId = (orgId: string): Group[] =>
    mockGroups.filter(g => g.orgId === orgId);
